services:
  redis:
    container_name: redis
    image: redis:6.0.6
    ports:
      - 6379:6379
    command: redis-server /etc/redis.conf
    volumes:
      - redis_data:/data
      - ./redis.conf:/etc/redis.conf
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    networks:
      - liurl_net

# 定义内部卷
volumes:
  redis_data: 
    name: redis_data

networks:
  liurl_net:
    external: true
    name: liurl_net