version: '3'
services:
  redis-master:
    image: redis:6.0.6
    container_name: redis-master
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./6380/conf/redis.conf:/etc/redis/redis.conf
      - redis_data_6380:/data
    ports:
      - 6380:6379
    privileged: true
    networks:
      - liurl_net
  redis-slave1:
    image: redis:6.0.6
    container_name: redis-slave-1
    ports:
      - 6381:6379
    privileged: true
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./6381/conf/redis.conf:/etc/redis/redis.conf
      - redis_data_6381:/data
    networks:
      - liurl_net
  redis-slave2:
    image: redis:6.0.6
    container_name: redis-slave-2
    ports:
      - 6382:6379
    privileged: true
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./6382/conf/redis.conf:/etc/redis/redis.conf
      - redis_data_6382:/data
    networks:
      - liurl_net
networks:
  liurl_net:
    external: true
    name: liurl_net

volumes:
  redis_data_6380: 
    name: redis_data_6380
  redis_data_6381: 
    name: redis_data_6381
  redis_data_6382: 
    name: redis_data_6382
