version: '3'
services:
  sentinel1:
    image: redis:6.0.6
    container_name: redis-sentinel-1
    ports:
      - 26379:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - /mnt/d/file_save/docker/docker_volumes/redis/sentinel/sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - liurl_net
  sentinel2:
    image: redis:6.0.6
    container_name: redis-sentinel-2
    ports:
    - 26380:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - /mnt/d/file_save/docker/docker_volumes/redis/sentinel/sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - liurl_net
  sentinel3:
    image: redis:6.0.6
    container_name: redis-sentinel-3
    ports:
      - 26381:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - /mnt/d/file_save/docker/docker_volumes/redis/sentinel/sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - liurl_net
networks:
  liurl_net:
    external: true
    name: liurl_net