version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql8
    privileged: true
    restart: always
    volumes:
      - /mnt/d/file_save/docker/docker_volumes/mysql/datadir:/var/lib/mysql
      - /mnt/d/file_save/docker/docker_volumes/mysql/conf/:/etc/mysql/
      - /mnt/d/file_save/docker/docker_volumes/mysql/docker/mysql/source:/docker-entrypoint-initdb.d
      - /mnt/d/file_save/docker/docker_volumes/mysql/mysql-files:/var/lib/mysql-files/
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      # 设置密码
      - "MYSQL_DATABASE=mydb"
      # 设置默认数据库
      - "TZ=Asia/Shanghai"
      # 设置时区
    ports:
      - 3306:3306
    # 设置端口