version: '3'
services:
  zookeeper:
    container_name: zookeeper
    networks:
      - liurl_net
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    networks:
      - liurl_net
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka   # 用ifconfig查询，或直接填写kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    volumes:
      - /mnt/d/file_save/docker/docker_volumes/kafka/docker.sock:/var/run/docker.sock

networks:
    liurl_net: