version: '3.5'
services:
  zookeeper:
    ## 镜像
    image: wurstmeister/zookeeper   
    container_name: zookeeper
    networks:
      - liurl_net
    ports:
      ## 对外暴露的端口号
      - "2181:2181"                 
  kafka:
    ## 镜像
    image: wurstmeister/kafka       
    container_name: kafka
    networks:
      - liurl_net
    volumes: 
        - /mnt/d/file_save/docker/docker_volumes/kafka/docker.sock:/var/run/docker.sock
    ports:
      - "9092:9092"
    environment:
      ## 修改:宿主机IP
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1         
      ## 卡夫卡运行是基于zookeeper的
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181       
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: 120
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DELETE_RETENTION_MS: 1000
  kafka-manager:
    ## 镜像：开源的web管理kafka集群的界面
    image: sheepkiller/kafka-manager                
    container_name: kafka-manager
    networks:
      - liurl_net
    ## 修改:宿主机IP
    environment:
        ZK_HOSTS: 127.0.0.1                         
    ports:  
      ## 暴露端口 9000这个端口冲突太多
      - "9009:9000"                                 

networks:
  liurl_net:  # 网络名
    name: liurl_net
    driver: bridge