version: '3'

services:
  portainer:
    restart: always
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9000:9000"
      - "8000:8000"
      - "9443:9443"
    volumes:
      # /var/run/docker.sock是你本地运行的docker的sock地址，否则进进入之后无法显示对应的local环境，也就是本地环境
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - TZ=Asia/Shanghai
      # the follow env do not work
      - admin-password=123456789qwe

volumes:
  portainer_data:  
    name: portainer_data
