name: syncToGitee
on:
  push:
    branches:
      - gh-pages
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          # 表示需要被同步的源端账户名，即我们 Github 的账户名
          src: 'github/lylyuanliang'
          # 表示需要同步到的目的端账户名，即我们 Gitee 的账户名
          dst: 'gitee/yybun'
          # 表示用于在目的端上传代码的私钥，然后将其保存在 Secrets 中
          dst_key: ${{secrets.GITEE_PRIVATE_KEY}}
          # 表示gitee token，然后将其保存在 Secrets 中
          dst_token: ${{secrets.GITEE_TOKEN}}
	        # 表示单一仓库同步
          # static_list: "learn-typescript"
	        # force_update 为 true 表示启用 git push -f 强制同步
          force_update: true
          # debug 为 true 表示启用 debug 开关，会显示所有执行命令
	        debug: true